# Generated by Django 4.2.7 on 2024-01-15 10:00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),  # Dependencia del módulo principal
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # ============================================================================
        # TABLA: PAYROLL_COMPANY
        # ============================================================================
        migrations.CreateModel(
            name='PayrollCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('whatsapp_webhook_token', models.CharField(max_length=255, unique=True, verbose_name='Token webhook WhatsApp')),
                ('whatsapp_phone_number', models.CharField(max_length=20, verbose_name='Número WhatsApp')),
                ('whatsapp_business_name', models.CharField(max_length=100, verbose_name='Nombre del negocio WhatsApp')),
                ('country_code', models.CharField(default='MEX', max_length=3, verbose_name='Código de país')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('payroll_frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('bimonthly', 'Bimestral')], default='monthly', max_length=20)),
                ('pricing_tier', models.CharField(default='starter', max_length=20, verbose_name='Tier de precios')),
                ('price_per_employee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por empleado')),
                ('premium_services', models.JSONField(default=dict, verbose_name='Servicios premium')),
                ('messaging_config', models.JSONField(default=dict, verbose_name='Configuración de mensajería')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.businessunit', verbose_name='Unidad de negocio')),
            ],
            options={
                'verbose_name': 'Empresa de Nómina',
                'verbose_name_plural': 'Empresas de Nómina',
                'db_table': 'payroll_company',
                'ordering': ['name'],
            },
        ),
        
        # ============================================================================
        # TABLA: PAYROLL_EMPLOYEE
        # ============================================================================
        migrations.CreateModel(
            name='PayrollEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=50, unique=True, verbose_name='Número de empleado')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('hire_date', models.DateField(verbose_name='Fecha de contratación')),
                ('job_title', models.CharField(max_length=100, verbose_name='Puesto')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('employee_type', models.CharField(choices=[('permanent', 'Permanente'), ('temporary', 'Temporal'), ('contractor', 'Contratista'), ('intern', 'Interno')], default='permanent', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario mensual')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tarifa por hora')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Número de cuenta')),
                ('clabe', models.CharField(blank=True, max_length=18, verbose_name='CLABE')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('nss', models.CharField(blank=True, max_length=11, verbose_name='NSS')),
                ('office_location', models.JSONField(default=dict, verbose_name='Ubicación de oficina')),
                ('working_hours', models.JSONField(default=dict, verbose_name='Horario de trabajo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='payroll.payrollcompany', verbose_name='Empresa')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollemployee', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'payroll_employee',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        
        # ============================================================================
        # TABLA: PAYROLL_PERIOD
        # ============================================================================
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=100, verbose_name='Nombre del período')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('bimonthly', 'Bimestral')], max_length=20, verbose_name='Frecuencia')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('calculated', 'Calculada'), ('approved', 'Aprobada'), ('disbursed', 'Dispersada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('total_employees', models.IntegerField(default=0, verbose_name='Total empleados')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total bruto')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total neto')),
                ('total_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total impuestos')),
                ('calculation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cálculo')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('disbursement_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de dispersión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Aprobado por')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='payroll.payrollcompany', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'db_table': 'payroll_period',
                'unique_together': {('company', 'start_date', 'end_date')},
                'ordering': ['-end_date'],
            },
        ),
        
        # ============================================================================
        # TABLA: PAYROLL_CALCULATION
        # ============================================================================
        migrations.CreateModel(
            name='PayrollCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario base')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas extra')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto horas extra')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonos')),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisiones')),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros ingresos')),
                ('gross_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingreso bruto')),
                ('isr_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ISR retenido')),
                ('imss_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IMSS empleado')),
                ('infonavit_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='INFONAVIT empleado')),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deducciones préstamos')),
                ('advance_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deducciones adelantos')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otras deducciones')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total deducciones')),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Neto a pagar')),
                ('imss_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IMSS patrón')),
                ('infonavit_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='INFONAVIT patrón')),
                ('total_employer_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo total patrón')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cálculo')),
                ('calculation_version', models.CharField(default='1.0', max_length=20, verbose_name='Versión de cálculo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_calculations', to='payroll.payrollemployee', verbose_name='Empleado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='payroll.payrollperiod', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Cálculo de Nómina',
                'verbose_name_plural': 'Cálculos de Nómina',
                'db_table': 'payroll_calculation',
                'unique_together': {('period', 'employee')},
                'ordering': ['employee__first_name', 'employee__last_name'],
            },
        ),
        
        # ============================================================================
        # TABLA: PAYROLL_ATTENDANCE
        # ============================================================================
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud entrada')),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud entrada')),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud salida')),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud salida')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tardanza'), ('half_day', 'Medio día'), ('remote', 'Remoto')], default='present', max_length=20, verbose_name='Estado')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas trabajadas')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas extra')),
                ('check_in_method', models.CharField(default='whatsapp', max_length=20, verbose_name='Método de entrada')),
                ('check_out_method', models.CharField(default='whatsapp', max_length=20, verbose_name='Método de salida')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='payroll.payrollemployee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'db_table': 'payroll_attendance',
                'unique_together': {('employee', 'date')},
                'ordering': ['-date', 'employee__first_name'],
            },
        ),
        
        # ============================================================================
        # TABLA: PAYROLL_EMPLOYEE_REQUEST
        # ============================================================================
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('sick_leave', 'Incapacidad'), ('personal_leave', 'Permiso personal'), ('overtime', 'Horas extra'), ('advance', 'Adelanto')], max_length=20, verbose_name='Tipo de solicitud')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('days_requested', models.IntegerField(verbose_name='Días solicitados')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notas de aprobación')),
                ('created_via', models.CharField(default='whatsapp', max_length=20, verbose_name='Creado vía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Aprobado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='payroll.payrollemployee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Solicitud de Empleado',
                'verbose_name_plural': 'Solicitudes de Empleados',
                'db_table': 'payroll_employee_request',
                'ordering': ['-created_at'],
            },
        ),
        
        # ============================================================================
        # ÍNDICES
        # ============================================================================
        
        # Índices para PayrollCompany
        migrations.AddIndex(
            model_name='payrollcompany',
            index=models.Index(fields=['country_code'], name='payroll_company_country_code_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcompany',
            index=models.Index(fields=['is_active'], name='payroll_company_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcompany',
            index=models.Index(fields=['business_unit'], name='payroll_company_business_unit_idx'),
        ),
        
        # Índices para PayrollEmployee
        migrations.AddIndex(
            model_name='payrollemployee',
            index=models.Index(fields=['employee_number'], name='payroll_employee_employee_number_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollemployee',
            index=models.Index(fields=['email'], name='payroll_employee_email_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollemployee',
            index=models.Index(fields=['is_active'], name='payroll_employee_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollemployee',
            index=models.Index(fields=['company'], name='payroll_employee_company_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollemployee',
            index=models.Index(fields=['supervisor'], name='payroll_employee_supervisor_idx'),
        ),
        
        # Índices para PayrollPeriod
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['company', 'status'], name='payroll_period_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='payroll_period_dates_idx'),
        ),
        
        # Índices para PayrollCalculation
        migrations.AddIndex(
            model_name='payrollcalculation',
            index=models.Index(fields=['period', 'employee'], name='payroll_calculation_period_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcalculation',
            index=models.Index(fields=['calculation_date'], name='payroll_calculation_date_idx'),
        ),
        
        # Índices para AttendanceRecord
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='payroll_attendance_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='payroll_attendance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['check_in_time'], name='payroll_attendance_checkin_idx'),
        ),
        
        # Índices para EmployeeRequest
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['employee', 'status'], name='payroll_request_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['request_type'], name='payroll_request_type_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['start_date', 'end_date'], name='payroll_request_dates_idx'),
        ),
    ] 