from ..lazy_imports import lazy_imports, register_module

# Register chatbot modules for lazy loading
lazy_imports.register('channel_config', '.channel_config')
lazy_imports.register('chat_state_manager', '.chat_state_manager')
lazy_imports.register('chatbot', '.chatbot')
lazy_imports.register('context_manager', '.context_manager')
lazy_imports.register('conversational_flow', '.conversational_flow')
lazy_imports.register('extractors', '.extractors')
lazy_imports.register('generate_embeddings', '.generate_embeddings')
lazy_imports.register('gpt', '.gpt')
lazy_imports.register('integrations', '.integrations')
lazy_imports.register('intents_handler', '.intents_handler')
lazy_imports.register('intents_handlers', '.intents_handlers')
lazy_imports.register('intents_optimizer', '.intents_optimizer')
lazy_imports.register('message_retry', '.message_retry')
lazy_imports.register('metrics', '.metrics')
lazy_imports.register('migration_check', '.migration_check')
lazy_imports.register('nlp', '.nlp')
lazy_imports.register('optimization_config', '.optimization_config')
lazy_imports.register('start_metrics', '.start_metrics')
lazy_imports.register('state_manager', '.state_manager')
lazy_imports.register('utils', '.utils')
lazy_imports.register('whatsapp_handler', '.whatsapp_handler')
lazy_imports.register('workflow', '.workflow')