# Generated by Django 4.2.23 on 2025-07-16 23:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_add_new_payroll_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent360AddonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Análisis de Talento 360°', max_length=100)),
                ('description', models.TextField(default='Evaluación integral de competencias y habilidades para optimizar el talento organizacional')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio de Análisis de Talento 360°',
                'verbose_name_plural': 'Servicios de Análisis de Talento 360°',
            },
        ),
    ]
